### ISSUE TITLE
wasm zero copy

### ISSUE THREAD

**Issue by ronag** [nodejs/llhttp#100]
Continuing from https://github.com/nodejs/undici/pull/711.

If `wasm_on_header_` and `wasm_on_body` instead returned `at` relative to the buffer passed to `execute` we could achieve zero copy. Both internally in llhttp and in the "user code"(undici).

**Comment by ronag** [comment]
@dnlup not sure how familiar you are with llhttp but pinging you as well just in case.

**Comment by indutny** [comment]
Again, this is already true on the level of C API. Wasm makes things trickier because you copy the input to the wasm memory and so get back the slice of wasm memory.

**Comment by ronag** [comment]
The challenge then is how map the `at` back to a index relative to the passed buffer.

**Comment by indutny** [comment]
You potentially can do it at the level of wasm module by subtracting pointers.
