### ISSUE TITLE
on_header_field and on_header_value

### ISSUE THREAD

**Issue by ronag** [nodejs/llhttp#102]
I assem to have made an incorrect assumption in that `on_header_field` and `on_header_value` are always called 1:1 after each other. I guess that is not the case? What are the semantics? Can e.g. `on_header_value` be called none or multiple times after a `on_header_field`?

i.e. is the following possible?

```
on_header_field
on_header_value
on_header_value
on_header_field
on_header_value
on_header_field
on_header_field
```

Refs: https://github.com/nodejs/undici/issues/737

**Comment by ronag** [comment]
Nevermind. Figured it out.

**Comment by pallas** [comment]
As a note for others who run into the same behavior: yes, it is possible. If the request is parsed in multiple, split buffers and one of the buffer boundaries falls within a header field or value, you'll get multiple on_header_field/on_header_value followed by an on_header_field_complete/on_header_field_value.
