### ISSUE TITLE
http_status

### ISSUE THREAD

**Issue by misery** [nodejs/llhttp#106]
Hi,

we tried to move from http_parser to llhttp. Is it possible to provide a `http_status`, too?

**Comment by indutny** [comment]
Hello!

Do you mean the methods for converting status code to string?

**Comment by indutny** [comment]
FWIW, `llhttp_get_status_code` can be used to get the status code out of the parser.

**Comment by misery** [comment]
Yes, I mean the enum to provide STATUS::OK instead of 200 and so on to avoid mistake with a wrong int.

**Comment by misery** [comment]
How can I do something like this? There is no HTTP_STATUS_ anymore.

```
int statusCode = llhttp_get_status_code();
if (statusCode == HTTP_STATUS_OK)
{
...
}
```

**Comment by ShogunPanda** [comment]
We can import statuses from https://github.com/nodejs/http-parser/blob/main/http_parser.h - Will send a PR soon!

**Comment by pallas** [comment]
LMK if you'd like any help with that!

**Comment by ShogunPanda** [comment]
@pallas Can you review the PR above?
