### ISSUE TITLE
What is SOURCE method?

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [nodejs/llhttp#107]
https://github.com/nodejs/llhttp/blob/master/src/llhttp/constants.ts#L160

I cannot find this method or reference anywhere, what is it?

**Comment by pallas** [comment]
It used to be used by Icecast.

**Comment by indutny** [comment]
Yeah, this is a way of llhttp being nice to other HTTP-based protocols :grin:

**Comment by IAmAnubhavSaini** [comment]
Thanks.
