### ISSUE TITLE
How to get the method/status code/http major/minor?

### ISSUE THREAD

**Issue by davidhcefx** [nodejs/llhttp#111]
## Description

By looking into the *compiled* header file `llhttp.h`, I figured out we could possibly access them directly, eg. `parser->method`.

```C
struct llhttp__internal_s {
  int32_t _index;
  void* _span_pos0;
  void* _span_cb0;
  int32_t error;
  const char* reason;
  const char* error_pos;
  void* data;
  void* _current;
  uint64_t content_length;
  uint8_t type;
  uint8_t method;
  uint8_t http_major;
  uint8_t http_minor;
  uint8_t header_state;
  uint8_t lenient_flags;
  uint8_t upgrade;
  uint8_t finish;
  uint16_t flags;
  uint16_t status_code;
  void* settings;
};
```

But that doesn't seem to be a safe and correct way to use it, because it's not part of the API. (The API provides related methods to `__wasm__` only)
https://github.com/nodejs/llhttp/blob/674cf94e975bea73970015eae272088b571cf368/src/native/api.h#L70-L98

## Suggestion

My suggestion would be to allow non-wasm users of calling those methods, or provide different implementations basing on whether it's a wasm compile or not.

**Comment by indutny** [comment]
Great idea. I believe we should make wasm methods public indeed. Would you be interested in contributing this to llhttp?

**Comment by vitaly-castLabs** [comment]
I second the motion. "Usage" paragraph gives one a false impression the library is a C HTTP parser, but then you realize there's no way to figure out if you got GET or POST. I'm off to find some other library I can use

**Comment by indutny** [comment]
Have you tried using `llhttp_get_method()`? The `llhttp.h` header file has lots of useful API methods.

Let me know if it works for you!

**Comment by vitaly-castLabs** [comment]
I can't use it as it's wrapped in `#if defined(__wasm__)` (along with other llhttp_get_ methods)

**Comment by indutny** [comment]
Oh right, this explains the absence of docs!

In any case, `parser->method` can be used as well. I should say in the docs that the fields that are not prefixed with underscore are public.

**Comment by davidhcefx** [comment]
> Great idea. I believe we should make wasm methods public indeed. Would you be interested in contributing this to llhttp?

@indutny Sorry for being unresponsive. Is it sufficient to simply remove the `#define`s in line 71 and 97?

https://github.com/nodejs/llhttp/blob/7d07fb43491fe89b0a0aad750a0b006f7414a842/src/native/api.h#L71-L97

**Comment by indutny** [comment]
I think it is a good idea. We can call these methods ABI stable in the comment and eventually come up with a documentation for them.

Thanks!

**Comment by davidhcefx** [comment]
@indutny I’m not sure about the ABI comments part, but here’s a PR!
