### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/llhttp#115]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

I also don't see any references to master in githbub workflows but there is a reference in https://github.com/nodejs/llhttp/blob/cc5adf399c116638cf1e07f937a67864149fb419/Makefile which would need to be changed.

Rename primary branch to main

**Comment by mhdawson** [comment]
@indutny any concerns about the rename from master->main ?

**Comment by mhdawson** [comment]
@indutny any objection if I flip this over?

**Comment by indutny** [comment]
No objections. Feel free to do it! Thanks!

**Comment by mhdawson** [comment]
Renamed, closing.
