### ISSUE TITLE
Why is there a zip file in the source code?

### ISSUE THREAD

**Issue by twose** [nodejs/llhttp#117]
![image](https://user-images.githubusercontent.com/25978241/121986103-898ffb80-cdc8-11eb-83b8-95219706591a.png)

Since release v6.0.2, I am confused, is there a reason for this?
Ping @indutny

**Comment by indutny** [comment]
Sorry for that. It should be removed in the next release. Fixed in bfb395b

**Comment by twose** [comment]
Thanks for your prompt reply :)
