### ISSUE TITLE
The llhttp__on_status function may not be called during the parsing of the statusline

### ISSUE THREAD

**Issue by ximu19163** [nodejs/llhttp#118]
The Status-Line was defined as "Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF" in rfc2616, but in many cases in actual use, there is no "Reason-Phrase", and the llhttp__on_status function will not to be called. 
Do you have a plan to deal with it？

**Comment by indutny** [comment]
Not really, the assumption that user's code can make is that the field starts empty and as `settings->on_status` is called - the extra data is concatenated with the string. Note that even when status is present - `settings->on_status` might be called several time during a single request if the TCP packet boundary will split the status string into two parts.
