### ISSUE TITLE
Port recent commits from http-parser

### ISSUE THREAD

**Issue by indutny** [nodejs/llhttp#12]
The tests and some changes from these commits has to be ported to llhttp:

* https://github.com/nodejs/http-parser/commit/01da95feade5e5612499f5374498e7968c1a4a82
* https://github.com/nodejs/http-parser/commit/cd88eef772b11b8934e37ec2cf83d56737e3cb0b
* https://github.com/nodejs/http-parser/commit/350258965909f249f9c59823aac240313e0d0120

cc @nodejs/http

**Comment by fanatid** [comment]
Was not able find good solution for https://github.com/nodejs/http-parser/commit/cd88eef772b11b8934e37ec2cf83d56737e3cb0b in #38 

Code was accidentally landed in https://github.com/nodejs/llhttp/commit/34835d37b94d6371456186e7f82b131d982e595b but then reverted. At least can be used as example.
