### ISSUE TITLE
pre-built C code

### ISSUE THREAD

**Issue by bsergean** [nodejs/llhttp#121]
Hi there,

We are users of http_parser, trying to move to llhttp. One hiccup we ran into is that integrating this library is harder for build-systems which don't have node.js pre-installed.

Should there be a folder where we have the generated code present ?
Or maybe instead, we have a release build process that generate a tarball with only the .c and the .h files ? / and this is what you see in the 'Release' tabs in github ? Or it's just a different kind of release, just like we have the .tar.gz and the .zip

Right now we are gonna solve our problems by embedding the generated .h and .c files directly in the project, but it makes updating to newer versions harder.

Thanks !

**Comment by indutny** [comment]
Hello!

Have you considered using [Releases page](https://github.com/nodejs/llhttp/releases)? Alternatively, there's a `release` branch that has `release/vx.y.z` tags on it.

Thanks!

**Comment by bsergean** [comment]
I actually downloaded a release tarball (the latest one), but there are no pre-built/pre-generated C files in it.

**Comment by indutny** [comment]
These are the contents of tarball for me:

<img width="199" alt="image" src="https://user-images.githubusercontent.com/238531/123361606-3cc4c700-d524-11eb-90dd-234317858fde.png">

There're no TS/JS file and only .c files and headers (more or less).

**Comment by bsergean** [comment]
I must have downloaded another tarball, generated by the github UI.

**Comment by bsergean** [comment]
For my use case, the one thing that's 'missing' in the release archive is a makefile / or cmakefile. Would you consider having one (if I submit a PR).

We used http-parser with a CMake ExternalProject (something that fetch a git repo content and run make or cmake on it).

**Comment by bsergean** [comment]
Ok in any case this can stay closed, as there is indeed pre-built C code. Maybe I'll make a separate issue for the make/cmake thing.

**Comment by bsergean** [comment]
FYI my attempt at the cmake thing is here -> https://github.com/nodejs/llhttp/pull/122
