### ISSUE TITLE
Release 6.0.5

### ISSUE THREAD

**Issue by bsergean** [nodejs/llhttp#123]
Hello,

Until 6.0.5 is released we cannot easily use the cmake way of building this library. Would you mind making a release to help with that please ?

The README file has a reference to show how to use cmake, and the version numbers should be updated as well.

```
FetchContent_Declare(llhttp
  URL "https://github.com/nodejs/llhttp/releases/download/v6.0.4/llhttp-release-v6.0.4.tar.gz")  # Using version 6.0.4
```

I've been trying to make a PR for that but my git fu failed me and I cannot rebase my fork.

Thanks !
- Benjamin

**Comment by bsergean** [comment]
https://github.com/nodejs/llhttp/pull/124/files

Here is the Readme PR

**Comment by bsergean** [comment]
Could we get a new release please ... ? Thanks !

**Comment by indutny** [comment]
Here you go! Sorry for a delay!

**Comment by bsergean** [comment]
Excellent, thank you !!
