### ISSUE TITLE
Using llhttp from OOP C++

### ISSUE THREAD

**Issue by rafalsk** [nodejs/llhttp#134]
hey there! Nice project we like it.

Calling it from C++ realm. In C++ realm we've got objects.

All these callbacks require RAW pointer to functions without Virtual Function Tables i.e. these cannot be member functions and can be either static functions or lambda functions without capture groups which is a bummer.

**Question**

Is there any field which we could use to store an pointer to 'this' a field? i.e. a field which would allow us to construct a trampoline to a member function of ours?

All the best, Wizards.

**Comment by pallas** [comment]
That's what the `llhttp_t.data` field is for.

**Comment by rafalsk** [comment]
@pallas, great stuff Wizards ([](https://gridnet.org)) playing today with it today LIVE... great stuff.

**Comment by pallas** [comment]
Awesome, glad you found it helpful. If you look at https://github.com/pallas/pyllhttp/ that's how the equivalent Python object is dereferenced. You *could* also use something like `container_of` too but if you're wrong, boom.
