### ISSUE TITLE
Please provide release/v6.0.6

### ISSUE THREAD

**Issue by sunpoet** [nodejs/llhttp#135]
Since v6.0.6 is released, could you please provide release/v6.0.6 just like previous versions.
Thanks.

**Comment by sunpoet** [comment]
@mcollina, could you please take a look at this? Thanks.

**Comment by mcollina** [comment]
I don't understand what you are asking for. v6.0.6 is tagged and released.

**Comment by indutny** [comment]
I can do that. Give me a second.

**Comment by indutny** [comment]
Basically, it pushes artifacts to `releases` branch when you do `npm version ...`.

**Comment by sunpoet** [comment]
> I don't understand what you are asking for. v6.0.6 is tagged and released.

See [release/v6.0.5](https://github.com/nodejs/llhttp/releases/tag/release%2Fv6.0.5) and its [asset](https://github.com/nodejs/llhttp/archive/refs/tags/release/v6.0.5.zip).

**Comment by indutny** [comment]
@sunpoet should be fixed now. Give it a try!

**Comment by sunpoet** [comment]
@indutny Got it. Thanks!

**Comment by mcollina** [comment]
@indutny thanks! Could you document the release process in case I have to do another security release?

**Comment by indutny** [comment]
Oh, it is pretty simple. Just do `npm version whatever` and push commit and tags.
