### ISSUE TITLE
HPE_CB_MESSAGE_COMPLETE meaning?

### ISSUE THREAD

**Issue by rafalsk** [nodejs/llhttp#137]
Hey there; we've been using llhttp to make our onboard reverse CORS-aware incentivized proxy ([gridnet.org](url)) more aware of what's being sent under the hood.

We've been getting lots of HPE_CB_MESSAGE_COMPLETE results on seemingly valid content/HTTP messages (especially on redirects) what's the meaning of these and other  members of the HPE_CB family of results?

**Comment by indutny** [comment]
Hello!

This error means that `on_message_complete` callback returned non-zero value and not `HPE_PAUSED` either. Does this match your source code?

**Comment by rafalsk** [comment]
@indutny It does match; kindly thank you for your assistance.
