### ISSUE TITLE
Multiple events for same data-chunk [Question]

### ISSUE THREAD

**Issue by rafalsk** [nodejs/llhttp#139]
sorry for being lazy and not testing it thoroughly but is LLHTTP supposed to fire say multiple on_chunk_complete events during single llhttp_execute if the provided data-set contains multiple chunks?  Also, while testing the content_length field is always 0.

**Comment by pallas** [comment]
Yes. Additionally, you may receive some callbacks multiple times, e.g. if some parsed span is split across multiple buffers. Content Length will be 0 if it is not parsed as part of the headers.
