### ISSUE TITLE
on_status versus on_status_complete

### ISSUE THREAD

**Issue by bsergean** [nodejs/llhttp#145]
While porting from http-parser to llhttp, I got bitten by the fact that there is a new on_status_complete callback that is important to register/hook, as in some rare situation the status code wasn't available yet in the other callback (on_status), while it was always available in on_status_complete.

One way to improve this for people like myself who will blindly re-assign the callbacks the way they are in http-parser, is maybe to just add a note in the documentation about this, to highlight the difference in behavior. In my version of http-parser there is no on_status_complete callback, so it must be an llhttp addition.

Any thoughts ? I could try to add a note in the doc for that as a PR when I get a chance.

ps: other than that this might have been our latest bug, so soon we should be able to switch fully to llhttp !

**Comment by pallas** [comment]
The original http-parser did not have this callback and I would guess also has this race condition. If you add the note, I think it'd be a great addition. And happy to hear that your transition to llhttp is mostly complete!

**Comment by bsergean** [comment]
Yes that makes sense now, we could have add our 'read and set status code in our internal data structure' hooked up later in other 'down the line' callbacks, but that's how the code was.

So technically, the race condition could have happened with http-parser, and maybe sometimes in our current code we fail to read correctly a status, so another bonus point for switching to llhttp.

**Comment by indutny** [comment]
❤️

**Comment by simplejackcoder** [comment]
Does this mean one could take this code + tcp/ip sockets and implement an http server? One of the things I keep being told is http parsing is hard, but I could use this code.

**Comment by simplejackcoder** [comment]
I also wonder how I could use this code to make this parser for other languages, like C#.

**Comment by bsergean** [comment]
For the C# question, I think it's a no, for the first one yes you can use this code to make an http server.

However those questions are off topic, this ticket was about a subtle documentation issue which is now addressed now.
