### ISSUE TITLE
please add generated c source code to release

### ISSUE THREAD

**Issue by forfuturedays** [nodejs/llhttp#165]
cool library! releasing ready-to-use portable c code would greatly simplify integration in a variety of situations and make it easier for projects to track the latest version. any other required code such as from llparse should be included with this too, although it looks like there isn't any currently. as it stands we have to install various heavy packages to build it in the first place, won't be able to integrate this cleanly in our build environment, and will need to look up the build process again in the future to update to a new version. /\

**Comment by pallas** [comment]
See https://github.com/nodejs/llhttp/tree/release which contains the .c/.h artifacts you're looking for.

**Comment by forfuturedays** [comment]
i see, thanks! i didn't think to look in the branches

**Comment by pallas** [comment]
No worries! Happy to help,
