### ISSUE TITLE
Give merge permissions to @ShogunPanda

### ISSUE THREAD

**Issue by ShogunPanda** [nodejs/llhttp#167]
As Node.js member involved in the HTTP stack, I'd like to have merge permissions here on llhttp not to be blocked when working on the parser.

**Comment by aduh95** [comment]
Currently, the permissions on this repo are set as such:

- `@indutny` has write access.
- `@nodejs/tsc` has read access.

So only one member has write access, that doesn't seem right – of course, the TSC being admin on the org also have full access, but it would be worth updating anyway, but imo it would be better not to have to use our admin privileges unless strictly necessary.
We should probably create a @nodejs/llhttp team and give it "Maintain" permission on this repo.

**Comment by mcollina** [comment]
I agree

**Comment by aduh95** [comment]
@ShogunPanda I think you can request to join the not-yet-created team on https://github.com/nodejs/admin/issues/705, and if there's no objection in seven days and at least one approval, it will be automatically accepted.

**Comment by aduh95** [comment]
Fixed by https://github.com/nodejs/admin/issues/705.
