### ISSUE TITLE
how can get the status code string 

### ISSUE THREAD

**Issue by aengusjiang** [nodejs/llhttp#172]

**Comment by aengusjiang** [comment]
for the old repo http_parse has a method to get the status code string which named http_status_str.
How about add the similar method  in this repo such as llhttp_status_str

**Comment by pallas** [comment]
Since you might receive the status in different chunks, you need to implement the `on_status` and `on_status_complete` callbacks to store the string yourself. The library doesn't allocate memory on its own.

**Comment by aengusjiang** [comment]
No. I mean that convert int status to string.
the http_parser.h line 421 in http_pasrer lib have the convert method， just a map.
https://github.com/nodejs/http-parser/blob/main/http_parser.h

**Comment by ShogunPanda** [comment]
Duplicate of https://github.com/nodejs/llhttp/issues/106
