### ISSUE TITLE
How to handle multiple requests in one packet with llhttp

### ISSUE THREAD

**Issue by l-w-p** [nodejs/llhttp#176]

**Comment by pallas** [comment]
When the initial message is complete, a parser with keep-alive set will restart in the initial state. It's up to you to clear out any state you may have had, although @indutny: is it worth adding an `on_reset` callback? If so, I could take a shot at that.

**Comment by l-w-p** [comment]
For example: one packet multiple requests

``` c
const char *str = 
"GET /index.html HTTP/1.1\r\nHost: www.test.com\r\n\r\n"
"GET /index.html HTTP/1.1\r\nHost: www.abc.com\r\n\r\n";

llhttp_init(parser, HTTP_BOTH, &settings);
llhttp_execute(parser, str, strlen(str));
```

When llhttp finishes parsing the www.test.com request, llhttp_execute() will return.
If we want to parse the www.abc.com request, how can I get the cursor to parse the progress using llhttp?

``` c
size_t last_req_len = parser->cursor - str;
llhttp_init(parser, HTTP_BOTH, &settings);
llhttp_execute(parser, str + last_req_len, strlen(str) - last_req_len);
```
