### ISSUE TITLE
How to judge that the HTTP version has been parsed with llhttp

### ISSUE THREAD

**Issue by l-w-p** [nodejs/llhttp#177]
For example: "GET /index.html HTTP/1.1\r\n"

When "H" appears ("GET /index.html H") it means the http version starts parsing.
When the last "1" appears ("GET /index.html HTTP/1.1"), it means the http version ends parsing.

How to judge that the HTTP version has been parsed with llhttp?

**Comment by pallas** [comment]
Check that major and minor are not both zero.

**Comment by l-w-p** [comment]
> Check that major and minor are not both zero.

Ambiguity occurs when http version is 1.0, it can correspond to the following two situations

1. minor version is real 0
2. minor version not parsed

Would adding callbacks for on_version and on_version_complete be a better solution?

**Comment by pallas** [comment]
Yes, I think adding `on_version_complete` makes sense.

**Comment by l-w-p** [comment]
Are there plans to add `on_version_complete` callback?

**Comment by ShogunPanda** [comment]
Yes, I'm working on it right now.
I hope to land a PR today.

It will also include on_method_complete.
