### ISSUE TITLE
Unexpected condition when parsing multiple requests in one packet

### ISSUE THREAD

**Issue by l-w-p** [nodejs/llhttp#191]
Version: llhttp-release-v6.0.9

Multi request in one packet, as bellow:

**POST and GET request**

``` c
const char *str1 = "POST /index.html HTTP/1.1\r\nconnection:close\r\ncontent-length: 1\r\n\r\n1\r\n\r\n"
                   "GET /index.html HTTP/1.1\r\nHost: www.test.com\r\nUser-Agent: curl/7.64.1\r\nAccept: */*\r\n\r\n";
llhttp_execute(parser, str1, strlen(str1);
```

when data is str1, llhttp only parser the first (POST) request, not parser the second (GET) request.

**GET and POST request**

``` c
const char *str2 = "GET /index.html HTTP/1.1\r\nHost: www.test.com\r\nUser-Agent: curl/7.64.1\r\nAccept: */*\r\n\r\n"
                   "POST /index.html HTTP/1.1\r\nconnection:close\r\ncontent-length: 1\r\n\r\n1\r\n\r\n";
llhttp_execute(parser, str2, strlen(str2);
```

Swap the two requests, when data is str2, llhttp will parser the all request(include the GET request and the POST request).

**Comment by ShogunPanda** [comment]
That is not a problem from llhttp.

If you look at your first request it contains `connection: close`, which means that the second request should not exist there.

In loose mode (the default), llhttp will discard all bytes not belonging to the first request. In strict mode, llhttp will throw an error.

Closing this.
