### ISSUE TITLE
Drop `obs_fold` support

### ISSUE THREAD

**Issue by DemiMarie** [nodejs/llhttp#198]
It has resulted in request smuggling vulnerabilities in the past, so dropping it reduces attack surface.

**Comment by ShogunPanda** [comment]
I agree, but unfortunately it is allowed by the spec and thus we cannot drop it.
Thanks for submitting this.

**Comment by DemiMarie** [comment]
> I agree, but unfortunately it is allowed by the spec and thus we cannot drop it. Thanks for submitting this.

I was hoping to have a specific error code, which Node would turn into a 400 error with a useful message.  This is also explicitly allowed by the spec.

**Comment by ShogunPanda** [comment]
Unfortunately this would complicate the parser too much, resulting probably in performance loss.
I'm sorry but we cannot do this.
If you happen to find a way that solves that, you're more than welcome to send a PR.
