### ISSUE TITLE
Unreachable code cause warnings

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [nodejs/llhttp#214]
Some tools are reporting warnings because of unreachable code sections:

https://github.com/nodejs/llhttp/blob/release/v8.1.0/src/llhttp.c
```
      /* UNREACHABLE */;
      abort();
```

What is the purpose of unreachable sections?
Is it possible to remove it (or make optional) in next release?

**Comment by ShogunPanda** [comment]
They are generated from [llparse](https://github.com/nodejs/llparse), of which I have limited understanding.
The best action here, if any, would be to disable the warning for such tools, if they support something like via magic comments in the code.
Which tools are you talking about? Can you provide me code, commands or the setup needed to reproduce the warning?
