### ISSUE TITLE
release tag name

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/llhttp#219]
While working on automating the update for this library, I 've noticed that the release tag name is `release/v8.1.0` while it should probably be `v8.1.0`, you can see from the url https://github.com/nodejs/llhttp/releases/tag/release%2Fv8.1.0`

**Comment by ShogunPanda** [comment]
Nope, it is like this on purpose:

* `v8.1.0` points to the source code (which is in TypeScript) at version 8.1.0
* `release/v8.1.0` points to the release (which is the generated C library) for version 8.1.0.

If you compare the two on GitHub you will immediately note the difference.
