### ISSUE TITLE
Using with cmake results in `VERSION "_RELEASE_" format invalid.`

### ISSUE THREAD

**Issue by bghgary** [nodejs/llhttp#220]
https://github.com/nodejs/llhttp#using-with-cmake

It looks like this is no longer possible without doing a replacement of `_RELEASE_` in CMakeLists.txt. Is this still supported?

**Comment by ShogunPanda** [comment]
Yes and no.
The most releases of llhttp (for sure series 7 and 8) substitute that variable with the proper version.
The trick is to change to download URL to be something `https://github.com/nodejs/llhttp/archive/refs/tags/release/v8.1.0.tar.gz`.

Can you give it a try and see if it works? And if it does, are you willing to provide a small PR to fix the docs?

**Comment by bghgary** [comment]
Yes, I got it working with the latest version. I'll submit a PR when I get a chance. Thanks!
