### ISSUE TITLE
llhttp 9.0.0 no longer accepts bare LF

### ISSUE THREAD

**Issue by guoye-zhang** [nodejs/llhttp#236]
The following response is rejected by the parser even with all lenient flags enabled:

"HTTP/1.1 200 OK\nContent-Length: 0\n\n"

**Comment by ShogunPanda** [comment]
I think this is an unwanted regression. I'll take a look soon.

**Comment by ShogunPanda** [comment]
You have to use `llhttp_set_lenient_headers`. The bug was not on the new flags but on old ones :)
