### ISSUE TITLE
Test mistake?

### ISSUE THREAD

**Issue by torsten-schenk** [nodejs/llhttp#238]
The test https://github.com/nodejs/llhttp/blob/main/test/request/content-length.md#no-error-on-simultaneous-content-length-and-transfer-encoding-identity-lenient specifies "Transfer-Encoding: identity" in the title but actually uses "Transfer-Encoding: chunked" in the test itself.

Expected: lenient parsing seems to accept Transfer-Encoding: chunked and Content-Length set at the same time. Is that the expected behaviour? Does it accept Transfer-Encoding: identity in lenient mode?

**Comment by ShogunPanda** [comment]
Yes, it was a typo on the test title.
According to the specs (both RFC 9112 which the most recent and RFC 7230 which llhttp implements) , `Content-Length` "SHOULD NOT" be sent when `Transfer-Encoding` is present. If it still happens, the latter should override the former.
llhttp is a bit stricter on this and forbids (when non in lenient mode) the conflict without attempting to resolve it. The value of the headers doesn't matter, their mere presence is enough.
