### ISSUE TITLE
Consider performance improvements comming from PR to llparse

### ISSUE THREAD

**Issue by ngrodzitski** [nodejs/llhttp#260]
Could you, please, look at the PR to llparse; https://github.com/nodejs/llparse/pull/58 ?
That gives a performance boost for llhttp by scanning http-fields faster.

Since llparse seems to be quite stable (last commit in main branch was more than a year ago), thus nobody watches it carefully, and the change was made for llhttp in mind it might be the case that here is the better place to ask to consider the change in llparse.

**Comment by lemire** [comment]
How did you assess the benefits experimentally?

PR https://github.com/nodejs/llparse/pull/58 bears on TableLookup. Correct? Is TableLookup used in llhttp directly or indirectly in llhttp? 


Is llhttp built with support for SSSE3 or SSE4.2? I see some [flag in the tests](https://github.com/nodejs/llhttp/blob/8498ef9d8b0e9539c8c331cf59213529287789e1/test/fixtures/index.ts#L67), but unless that's also used by Node.js when building for production use, then that's not very useful.

**Comment by ShogunPanda** [comment]
Not considering this for now.
Nobody is maintaining llparse at the moment so we don't really know the infrastructure risk associated with it.
