### ISSUE TITLE
Pointers on how to build

### ISSUE THREAD

**Issue by espositofulvio** [nodejs/llhttp#30]
Hi,
I'm trying to make python bindings of llhttp. I had a couple of attemps writing the minimum required to get it to execute parsing without calling any callback. Got two implementation, one using C++ and pybind11 and the other in plain C. In both cases I dropped the generated files from the last commit into my project and tried to build. Interestingly enough, when comparing to httptools (a python binding for http_parser) without any callback involved, httptools is faster than my binding. In the begining I thought it was pybind11 introducing unneeded overhead, but I'm starting to think it's something to do with compilation flags or #define. Could you provide any indication on how to compile llhttp?

**Comment by indutny** [comment]
Hello!

I think it would be safe to grab pre-built sources from: https://github.com/nodejs/llhttp/releases and just use the `.c` and `.h` files in your build.

I don't think there are any special build flags that you have to use. Nevertheless, if there is any issue with the approach above - please let us know!

Thanks for using it!

**Comment by indutny** [comment]
Hello!

Thanks for giving it a try. Could you share the numbers/benchmark results that you see?

There are no special defines, but the performance of built library would certainly benefit from `-O3` compiler flag.

**Comment by espositofulvio** [comment]
Hi Fedor,

Here is my benchmark code, I've taken the sample requests from the llhttp repo:

```python
import httptools
import pyllhttp
import timeit

req1 = b'''GET /wp-content/uploads/2010/03/hello-kitty-darth-vader-pink.jpg HTTP/1.1\r\nHost: www.kittyhell.com\r\nUser-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; ja-JP-mac; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3 Pathtraq/0.9\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: ja,en-us;q=0.7,en;q=0.3\r\nAccept-Encoding: gzip,deflate\r\nAccept-Charset: Shift_JIS,utf-8;q=0.7,*;q=0.7\r\nKeep-Alive: 115\r\nConnection: keep-alive\r\nCookie: wp_ozh_wsa_visits=2; wp_ozh_wsa_visit_lasttime=xxxxxxxxxx; __utma=xxxxxxxxx.xxxxxxxxxx.xxxxxxxxxx.xxxxxxxxxx.xxxxxxxxxx.x; __utmz=xxxxxxxxx.xxxxxxxxxx.x.x.utmccn=(referral)|utmcsr=reader.livedoor.com|utmcct=/reader/|utmcmd=referral\r\n\r\n'''

req2 = b'''POST /joyent/http-parser HTTP/1.1\r\nHost: github.com\r\nDNT: 1\r\nAccept-Encoding: gzip, deflate, sdch\r\nAccept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nReferer: https://github.com/joyent/http-parser\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\nCache-Control: max-age=0\r\n\r\nb\r\nhello world\r\n'''


def bench_httptools_1():
    httpparser = httptools.HttpRequestParser(None)
    httpparser.feed_data(req1)


def bench_httptools_2():
    httpparser = httptools.HttpRequestParser(None)
    httpparser.feed_data(req2)




def bench_pyllhttp_1():
    parser = pyllhttp.HttpRequestParser(None)
    parser.feed_data(req1)


def bench_pyllhttp_2():
    parser = pyllhttp.HttpRequestParser(None)
    parser.feed_data(req2)


if __name__ == "__main__":
    print(timeit.timeit('bench_httptools_1()', setup='from __main__ import bench_httptools_1'))
    print(timeit.timeit('bench_httptools_2()', setup='from __main__ import bench_httptools_2'))
    print(timeit.timeit('bench_pyllhttp_1()', setup='from __main__ import bench_pyllhttp_1'))
    print(timeit.timeit('bench_pyllhttp_2()', setup='from __main__ import bench_pyllhttp_2'))
```

numbers are for the C++ + pybind11 version:
httptools1: 2.6346202000000005
httptools2: 2.577200099999999
pyllhttp1: 3.1190481000000005
pyllhttp2: 3.2208406000000025

for the plain C version (still incomplete, but runs this test):
httptools1: 2.5808126000000016
httptools2: 2.532094200000003
pyllhttp1: 3.235533100000005
pyllhttp2: 3.2765143999999964

As you see, my two implementations are on par for performance, so I'm ruling out pybind11 as the culprit.

In both cases the extensions are not really complicated, they are boilerplate around the code to run llhttp and very much like the httptools implementation (which uses Cython) the logic is the same, I also used the same interfaces to give user an easier migration path. I don't have any public repo, I'd like to resolve this issue before publish something, but I can put them up if you want to have a quick look.
I also thought it was WSL at some point, but the parser is cpu bound and WSL has issues with I/O while it's very good for CPU bound work.

**Comment by espositofulvio** [comment]
Well, it turned out I have a logic error when not passing in an object with callbacks which invoked a slow path in building the python parser object containing llhttp. So in the base case I managed to get the advertised performance compared to httptools. Now I have to resolve another issue whereby object construction when passing in callbacks is really slow. I'll close this issue anyway.

**Comment by indutny** [comment]
Awesome. Sorry, I was not able to look into this since last our interaction. Glad that you have identified the culprit, though!

Please share your progress with us!

**Comment by espositofulvio** [comment]
I certainly will, as soon as I have fixed the other performance issue I will publish a link here as well :)
