### ISSUE TITLE
Version 9.2.1 is missing or still unreleased

### ISSUE THREAD

**Issue by jellelicht** [nodejs/llhttp#346]
It seems that version 9.2.1, as used in Node.js 20.12.1 ([CHANGELOG](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.12.1)), is missing a tag or release on this repo.
Would it be possible to push a v9.2.1 tag? Thanks in advance, and thanks for maintaining llhttp :+1:

**Comment by Uzlopak** [comment]
@addaleax

Could you please add the changes to our main branch?

**Comment by ShogunPanda** [comment]
Hello. I'm currently on public release of llhttp as we speak. Will keep you posted.

**Comment by ShogunPanda** [comment]
I just released 9.2.1. Sorry for the wait.
