### ISSUE TITLE
Linux issue with the SheBang in bin/generate.ts

### ISSUE THREAD

**Issue by damonearp** [nodejs/llhttp#35]
I'm running `make release` to generate the c source code to use in a project. I'm working in Linux and I have to tweak the shebang in `bin/generate.ts`.

### Environment
* Debian 10.2 (Docker Container `debian:10-slim`)
* llhttp-2.0.1

### What happens?
```sh
$ make
./bin/generate.ts
/usr/bin/env: 'npx ts-node': No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
make: *** [Makefile:57: generate] Error 127
```

### Workaround for Linux
```sh
$ sed -i 's/env npx/env -S npx/' bin/generate.ts
$ make
./bin/generate.ts
...
```

Thanks for the great tool!

**Comment by fanatid** [comment]
@damonearp fixed now, thank you for solution. I also faced with this issue.

**Comment by indutny** [comment]
Thank you @damonearp ! Unfortunately I haven't seen this issue before and didn't give you due credit when landing @fanatid 's PR. Still please know that your advice was very welcome!
