### ISSUE TITLE
llhttp release 9.2.1 does not match bundled sources in node 20.12.1

### ISSUE THREAD

**Issue by jellelicht** [nodejs/llhttp#355]
See title.
To give a demonstrative small example:
Bundled in Node, in `deps/llhttp/src/api.c`, `llhttp_reset`:
  `uint8_t lenient_flags = parser->lenient_flags;`

Release archive 9.2.1, in `src/native/api.c`, `llhttp_reset`:
  `uint16_t lenient_flags = parser->lenient_flags;`

NB, there are other differences as well, but I'm guessing something went wrong cutting a release branch. If needed, I can provide a comprehensive diff.

Could a (re?)release be made for llhttp, matching the sources bundled with Node 20.12.1? Thanks in advance

**Comment by ShogunPanda** [comment]
Sure, I'll take care of it tomorrow, releasing `9.2.2`.

**Comment by ShogunPanda** [comment]
Hello, I just check the source code.
Sorry for having noted this earlier, but both llhttp release are fine.

I just noticed you mentioned Node 20.x. That release line ships llhttp 8.x. llhttp 9.x is only included in Node 21.x (and 22.x in few weeks). and cannot be backported to Node 20.x.

**Comment by jellelicht** [comment]
Oh wow, that's a bit of an oversight then, I guess.
See attached screenshot for where my confusion stems from:
![screenshot_2024-04-10-230547](https://github.com/nodejs/llhttp/assets/251382/fa5b974a-8bf2-4d41-b0e3-cfae09a4721a)
Would you kindly confirm exactly which tagged version of llhttp was shipped with the Node v20.12.1 release, if not the 9.x series? Thanks for all the work, and sorry once again for all the overhead
