### ISSUE TITLE
Q: skip tabs in header_value_discard_rws?

### ISSUE THREAD

**Issue by fanatid** [nodejs/llhttp#39]
I'm not familiar with HTTP spec, but while trying done #38 I found that `header_value_discard_rws` skip only whitespaces, while `header_value_discard_lws` / `header_value_discard_ws` also skip tabs. Is this OK?

https://github.com/nodejs/llhttp/blob/v2.0.1/src/llhttp/http.ts#L485-L486

--
sorry for silly questions

**Comment by indutny** [comment]
I have no idea. Would appreciate a research of RFC on this!

**Comment by indutny** [comment]
You know what, I don't think that `header_value_discard_rws` is actually needed anymore. Going to remove it if the tests pass without it.
