### ISSUE TITLE
Unused llparse_blobs in llhttp.c causing compilation errors

### ISSUE THREAD

**Issue by codebytere** [nodejs/llhttp#43]
When this repo is built, the generated `llhttp.c` file contains unused `llparse_blob`s; at present `llparse_blob1[]`, `llparse_blob7[]`, `llparse_blob9[]`, and `llparse_blob10[]` are unused.

This causes compilation failures in Electron.js, since we do not allow unused variables. I'm happy to open a PR to address this myself if i can be pointed in the right direction!

cc @indutny

**Comment by fanatid** [comment]
It was fixed few hours ago in llparse: https://github.com/nodejs/llparse/pull/34
llparse@6.2.1 was released, now everything should be fine :)

**Comment by codebytere** [comment]
@fanatid thanks! appreciated 🙇‍♀
