### ISSUE TITLE
Parse Error: Expected HTTP/' when rtsp response

### ISSUE THREAD

**Issue by 7956968** [nodejs/llhttp#464]
RTSP/1.0 200 OK\r\n
CSeq: 1\r\n
Server: WSS6\r\n
Date: Thu, Aug 15 2024 06:25:16 GMT\r\n
Transport: RTP/AVP/UDP; unicast; client_port=1000-1001; server_port=450-451\r\n
Session: A213D9AC\r\n\r\n

**Comment by ShogunPanda** [comment]
You are right.

@Uzlopak I lean into introducing a new leniency flag to accept `RTSP/` or `ICE/` responses. I wouldn't allow it by default since it would allow a HTTP response to be replied by RTSP, which is not a good idea. WDYT?

**Comment by 7956968** [comment]
agree,thank you

**Comment by 7956968** [comment]
maybe you can add api like" get protocol" or any other something.:-)

**Comment by Uzlopak** [comment]
What is RTSP?

**Comment by 7956968** [comment]
In my opinion, the only difference is “RTSP” and “HTTP”

**Comment by ShogunPanda** [comment]
@Uzlopak https://en.wikipedia.org/wiki/Real-Time_Streaming_Protocol

@7956968 Yes, we are probably missing it.
