### ISSUE TITLE
Bindings to other languages

### ISSUE THREAD

**Issue by derekargueta** [nodejs/llhttp#55]
I'm curious if this project is open to contribution work for adding bindings to other languages, i.e. Python and Ruby. It'd be pretty cool for packages across these languages, including the existing npm package, to share the same core parsing code.

**Comment by indutny** [comment]
That'd be nice!

**Comment by ChillFish8** [comment]
As a add on to this, In the process of writing bindings for Python and Rust ive had alot of issues with finding any documentation other than rooting through the header file, if you have and link to documentation would be alot of help for someone like me who doesnt do much C

**Comment by bryanp** [comment]
I'm interested in writing bindings for Ruby, but having trouble conceptualizing how to make that happen with `llparse` in the mix. For example, `build/c/llhttp.c` doesn't contain implementation for things like `llhttp__on_body`. Are we expected to write these implementations or am I missing how the pieces come together?

**Comment by bryanp** [comment]
@indutny That's exactly what I needed, thanks! I hadn't noticed `make release`.

The documentation in the header file should be sufficient but I'll reach out in this thread if I hit questions.

**Comment by bryanp** [comment]
I have an implementation more or less complete, but am hitting a segfault in some uses. Took the time to distill the extension down to the simplest reproduction of the crash. At this point it isn't obvious to me what the underlying problem is, but I thought it might be helpful to post it here for another pair of eyes. Hopefully it's something obvious 😅 

Here's the simple extension annotated with a few notes (I also included console output and the crash log):

https://gist.github.com/bryanp/adf8e3325b164f916b862d9cee7e1461

**Comment by indutny** [comment]
@bryanp upon a first look - the problem could be with the `settings` object. You might want to either allocate it with `malloc` or to make it a `static` variable so that it doesn't get filled with garbage after `rb_llhttp_allocate` exists.

**Comment by bryanp** [comment]
@indutny yep, using `malloc` solved the problem. Hope to release this in the next few days, I'll post a link here when I do.

**Comment by bryanp** [comment]
Well, I found time to wrap up an initial version today: https://github.com/metabahn/llhttp. Thanks for your help @indutny!

**Comment by indutny** [comment]
@bryanp looks nice! np!

If I may give an advice - you probably want to `free()` the `settings` before freeing the parser :wink: Otherwise it'll leak memory.

**Comment by bryanp** [comment]
Oh, right! I'll get that fixed.

**Comment by victoraugustolls** [comment]
> @bryanp looks nice! np!
> 
> If I may give an advice - you probably want to `free()` the `settings` before freeing the parser wink Otherwise it'll leak memory.

Glad I found this so I can change it here: https://github.com/MagicStack/httptools/pull/56

:D

**Comment by pallas** [comment]
For a Python binding, see https://github.com/pallas/pyllhttp + https://pypi.org/project/llhttp

**Comment by indutny** [comment]
We have Python and Ruby bindings now. Fantastic work y'all!
