### ISSUE TITLE
HTTP 1.1 pipeline

### ISSUE THREAD

**Issue by xcyl** [nodejs/llhttp#57]
Can llhttp support pipeline? 
I can't find the instructions for this.
And how do I know how many bytes are being processed when I call llhttp_execute.

**Comment by indutny** [comment]
Hello!

llhttp fully supports HTTP/1.1 and thus supports pipelining as well. Calling `llhttp_execute` consumes all input bytes unless it encounters an error. Please refer to [api.h](https://github.com/nodejs/llhttp/blob/master/src/native/api.h) for further explanation on callbacks that notify caller about new requests.
