### ISSUE TITLE
Content-Length Mismatch

### ISSUE THREAD

**Issue by ronag** [nodejs/llhttp#62]
Not sure if this should fall into the responsibility of llhttp but it might make sense to error if the parsed body does not match the content-length header, if such was provided.

Also a question, does llhttp permit body on requests without content-length nor transfer-encoding? If so, how does it determine end of message? Trailing CRLF?

**Comment by indutny** [comment]
llhttp is somewhat stricter than other parsers. It doesn't allow presence of both `Transfer-Encoding` and `Content-Length`. Thus it should not be possible to encounter the mismatch.

The requests without either headers are of course allowed as per HTTP specification. The behavior of parser depends on the method type and request/response side. I encourage you to check this in specification as there is some tricky behavior described there.
