### ISSUE TITLE
Performance requests

### ISSUE THREAD

**Issue by ronag** [nodejs/llhttp#64]
Would be nice if:

- A flag that would cause llhttp to automatically lowercase response headers, so that higher level libraries do not need to perform an additional iteration over headers.

- Parse and include "keep-alive: timeout (\d+)s" in `kOnMessageHeadersComplete`, e.g. by changing the type of `shouldKeepAlive` to an integer,  so that higher level libraries do not need to perform an additional iteration over headers.

Refs: https://github.com/mcollina/undici/pull/337/files#diff-50cfa59973c04321b5da0c6da0fdf4feR542-R566

**Comment by indutny** [comment]
I'll investigate, but the second is possible. As for the first one, llhttp does not modify the incoming data - it simply isn't possible for it to emit data that isn't the part of the input. Sorry!

**Comment by indutny** [comment]
Is `keep-alive` header a part of this draft https://tools.ietf.org/id/draft-thomson-hybi-http-timeout-01.html ?

**Comment by ronag** [comment]
https://tools.ietf.org/html/draft-thomson-hybi-http-timeout-03#section-2
https://tools.ietf.org/html/rfc7230#appendix-A.1.2

On server side it's supported by nginx and more recently Node. Probably more that I am not aware. We want to add support for it in the Node core client as well.

It resolves a problem that otherwise cannot be workaround in terms of a connection close race between server and client.

**Comment by ronag** [comment]
https://github.com/nodejs/node/pull/34561

**Comment by ronag** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout

**Comment by indutny** [comment]
Excellent! Thank you for sharing the references.

What do you think about the following plan: I'll make this change in a branch and we'll see how much difference it makes for undici. If there is a performance improvement for it - we'll polish the feature and release it, otherwise - we'll call the experiment a failure. Does this sound reasonable?

**Comment by ronag** [comment]
Sounds great. Thank you for helping out on this.

**Comment by indutny** [comment]
@ronag could you give a try to [this branch](https://github.com/nodejs/llhttp/tree/feature/gh-64) please?

**Comment by ronag** [comment]
Sure. Just need to figure out how to make a node build with it.

**Comment by indutny** [comment]
Oh, right. Sorry!

I'd clone the repo, checkout the branch, run `npm install` and `make release`, and then copy over the contents of `release/*` into `deps/llhttp` in Node.js folder.

**Comment by ronag** [comment]
Hm, I did that, copied to deps/llhttp and overwrote the old files and confirmed they contain the changes. Did a `./configure --ninja` and `make -j4`. However, Node seems to still be running with previous version... Any ideas? I'm not too good with the Node build system

**Comment by ronag** [comment]
Found it! `node_http_parser` needs some tuning as well.

**Comment by indutny** [comment]
You have to patch up node so that it makes it an integer. Let me see what change would do it.

**Comment by indutny** [comment]
Oh, you found it! Great!

**Comment by ronag** [comment]
hm, I'm unable to get useful results... running the built version of Node is significantly slower (2x) than `nvm install`. :/

**Comment by ronag** [comment]
Ok, now I ran it without the changes from the branch and the performance is back. Is it expect that should have such significant performance impact? Maybe I'm doing something wrong.

**Comment by indutny** [comment]
I don't think there should be significant performance issues... (the benchmarks in llhttp are unaffected by the change as far as I can tell.) It is likely that something just went wrong with the build.

**Comment by ronag** [comment]
LLPARSE_DEBUG?

**Comment by indutny** [comment]
It should not be used for release builds if this is what you are asking about.

**Comment by ronag** [comment]
No I thought maybe I had to pass a flag to disable it. But noticed it's disabled by default. Hm... I'm at loss.

**Comment by indutny** [comment]
Did you compile Node.js master or the same version as what you are using through nvm? Also, why do you run `./configure --ninja` and build with a `make` (and not `ninja`). Sounds like you can drop `--ninja`.

**Comment by ronag** [comment]
I complied Node with and without the changes (no nvm this time). The perf diff occurs.

> Also, why do you run ./configure --ninja and build with a make (and not ninja)? Sounds like you can drop --ninja.

I have no idea. I am not very good with build stuff.

**Comment by ronag** [comment]
```js
undici$ time /Users/ronagy/GitHub/nxtedition/node/out/Release/node llhttp.js 
real    0m9.084s
user    0m4.844s
sys     0m2.387s

undici$ time /Users/ronagy/GitHub/nxtedition/node/out/Release/node llhttp.js 
real    0m7.161s
user    0m2.085s
sys     0m0.636s
````

First one with llhttp changes, second one without

**Comment by ronag** [comment]
Changes in node:

<img width="525" alt="Screen Shot 2020-08-18 at 21 27 02" src="https://user-images.githubusercontent.com/3065230/90556672-95576500-e199-11ea-9ee7-086be046a3fc.png">

**Comment by indutny** [comment]
Could you share the `llhttp_bench.js` in a gist?

**Comment by ronag** [comment]
https://github.com/mcollina/undici/pull/342/files

**Comment by ronag** [comment]
Sorry! I think I made a mistake in undici.

**Comment by ronag** [comment]
Ok, here we go:

First one is with the changes and second one without:

```js
undici$ time /Users/ronagy/GitHub/nxtedition/node/out/Release/node llhttp_bench.js 

real    0m6.338s
user    0m2.091s
sys     0m0.639s
undici$ time /Users/ronagy/GitHub/nxtedition/node/out/Release/node llhttp_bench.js 

real    0m7.391s
user    0m2.076s
sys     0m0.642s
undici$ 
```

It's a bit of an unrealistic benchmark since the test server is responding with 1000 headers but it does show there is a diff.

**Comment by indutny** [comment]
So... it is better?

**Comment by ronag** [comment]
> So... it is better?

yes, ~5% better

**Comment by indutny** [comment]
Looks about the same with sufficient number of runs:

```
new llhttp: n=100 mean=49943.697 stddev=1994.497
old llhttp: n=100 mean=49818.511 stddev=1175.314
new llhttp: n=100 mean=49716.333 stddev=984.585
old llhttp: n=100 mean=49305.306 stddev=1173.042
```

Here's the modified benchmark script: https://gist.github.com/indutny/b972581054a30d0773497a94845fa9aa

**Comment by indutny** [comment]
That being said, I'm looking forward for seeing how this benchmark will run on modified undici that leverages the parsed header value.

**Comment by ronag** [comment]
modified
```js
n=10 mean=37967.646 stddev=1825.623
n=11 mean=37959.568 stddev=1740.851
n=12 mean=37920.880 stddev=1671.669
n=13 mean=37985.404 stddev=1621.567
n=14 mean=38082.097 stddev=1601.000
n=15 mean=38191.946 stddev=1600.393
n=16 mean=38336.339 stddev=1647.397
n=17 mean=38347.190 stddev=1598.799
n=18 mean=38441.682 stddev=1601.856
n=19 mean=38572.819 stddev=1655.426
n=20 mean=37980.719 stddev=3043.760
```

unmodified
```js
n=10 mean=37049.327 stddev=1970.533
n=11 mean=37152.343 stddev=1906.863
n=12 mean=37245.497 stddev=1851.640
n=13 mean=37096.669 stddev=1852.196
n=14 mean=36297.388 stddev=3389.784
n=15 mean=35838.924 stddev=3696.925
n=16 mean=35399.625 stddev=3963.307
n=17 mean=35454.777 stddev=3851.296
n=18 mean=35349.347 stddev=3767.946
n=19 mean=35047.386 stddev=3884.770
n=20 mean=35126.518 stddev=3802.084
```

**Comment by indutny** [comment]
Could you run it for longer time @ronag ? The standard deviation is quite significant and given low `n` - there must be a lot of noise in the `mean` (noise goes of as `1/sqrt(n)`). It should be safer to compare `n=100` (or even `n=200`) results.

Could you also share the node.js patch that you are using? I'd like to do the benchmarks runs on a beefy server as well.

**Comment by ronag** [comment]
https://github.com/nxtedition/node/commit/4e460f33b424a3e47d3e9fd37b101b51d7182244

**Comment by ronag** [comment]
My computer is useless for benchmarks unfortunately. Have the same problem with undici benchmarks.

**Comment by indutny** [comment]
Thanks! I'll give it an extended run and report back to you.

**Comment by indutny** [comment]
Here are the results:

```
unmodified node/unmodified undici: n=400 mean=26304.847 stddev=462.045
modified node/unmodified undici: n=400 mean=25074.248 stddev=329.500
modified node/modified undici: n=400 mean=25741.999 stddev=467.845
```

Looks like there is no significant improvement, and in fact it is worse than with unpatched node.

**Comment by ronag** [comment]
That's interesting. I guess doing the keep-alive parsing is faster in Javascript. Weird.

Thanks a lot for trying this. Much appreciated. I might dig into this at some point in the future to try and understand why it's slower.

**Comment by indutny** [comment]
Sure thing! I'm keeping the branch in llhttp for now. Thanks!
