### ISSUE TITLE
Why are you using so many 'abort()' in ./build/c/llhttp.c

### ISSUE THREAD

**Issue by wangxi19** [nodejs/llhttp#70]
llhttp library is used in other program as an auxiliary tool in most cases. any 'abort()' used in this library can crash whole program.

**Comment by wangxi19** [comment]
And I found other issue. in README.md line 3 `llhttp_t parser;`. the parser was declared but wasn't initialized. that will lead to execute error in `enum llhttp_errno err = llhttp_execute(&parser, request, request_len);`. Because the value of parser's 'error' is uninitialized value and isn't 0

**Comment by indutny** [comment]
@wangxi19 have you found `llhttp_init` call in the readme? This should be sufficient to initialize the structure.

Use of `abort()` is not prohibited per se, and if you'll look closely all of the aborts are not actually reachable. They are there for a consistency check of the generated code. If any of them would be triggered the state wouldn't be reliable anyway.
