### ISSUE TITLE
How to access HTTP fields like User-Agent? 

### ISSUE THREAD

**Issue by gerald-dotcom** [nodejs/llhttp#71]
I'm trying to figure out this but fails to see any information regards accessing such fields. 
I know there is a buffer called Data but am not sure what it supposed to do. 

I was only able to access basic fields like Content-Length etc

**Comment by indutny** [comment]
Hello!

There are two header callbacks in [`settings` object](https://github.com/nodejs/llhttp/blob/8b3939e29a01ffbf9e481a76db81e372f0fb2f0c/include/llhttp.h#L264-L265) that should help with this.

**Comment by s215281942** [comment]
indutny can you please give more info or an example please.

**Comment by indutny** [comment]
I sure can. [Here's](https://github.com/nodejs/node/blob/d233f10f0317bdecc143b409681c1db53eb9eaac/src/node_http_parser.cc#L247-L292) how it is used in Node.js, and [here's](https://github.com/nodejs/llhttp/blob/95321e281c1e4036660a4da5f5d6816fe6f24634/test/fixtures/extra.c#L78-L89) how it is used in the tests for llhttp.

`on_header_field`/`on_header_value` are the callbacks you are looking for. They receive the slice of the parsed string. If you need just the value of the user-agent - you can:

1. do `strcmp` on the header name
2. set a flag in some struct associated with this instance of `llhttp_t`
3. on next `on_header_field` invocation - check the flag and allocate and copy the value

**Comment by s215281942** [comment]
Thank you
