### ISSUE TITLE
Position in buffer after execution of llhttp_execute(),  which has returned HPE_PAUSED_UPGRADE

### ISSUE THREAD

**Issue by pkpro** [nodejs/llhttp#86]
Hello there!

Is there a way to get the possition in buffer, at which parsing stopped/paused when "upgrade" was detected?

llhttp_execute(&parser, (const char*)buff, len);

I mean this **buff** buffer.

It could be like several KB large, the length of the buffer is known, but at which position the data for upgraded protocol starts is a mistery.

Thanks,
Pavel.

**Comment by indutny** [comment]
Hey @pkpro!

Have you looked into `error_pos` property yet? I think it might be what you are looking for!

Thanks!

**Comment by pkpro** [comment]
Thank you! That's it. I'll close this issue now.
