### ISSUE TITLE
HTTP2(h2) upgrade is not recognized by parser.

### ISSUE THREAD

**Issue by pkpro** [nodejs/llhttp#87]
Hello again,
The parser correctly recognizes h2c upgrade method from HTTP1.1, however the upgrade for h2 (within TLS) aka
**PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n**
Does not work returning HPE_INVALID_METHOD.
Can you please add it?
Thanks!

**Comment by pallas** [comment]
What version are you using? I added that functionality recently, but I don't think a new version has been created since then. See #80

**Comment by pkpro** [comment]
I'm using 3.0.0

#define LLHTTP_VERSION_MAJOR 3
#define LLHTTP_VERSION_MINOR 0
#define LLHTTP_VERSION_PATCH 0

Closing this issue as a duplicate
