### ISSUE TITLE
Is there existing any method to parsing both request and response at once?  v2.2.0

### ISSUE THREAD

**Issue by wangxi19** [nodejs/llhttp#91]
I saw that '/* Initialize the parser in HTTP_BOTH mode, meaning that it will select between
 * HTTP_REQUEST and HTTP_RESPONSE parsing automatically while reading the first
 * input.
 */' in README.md,
But if I parse both request and response in onece llhttp_execute call(the http message like this 'GET / HTTP1.1\r\n\r\nHTTP/1.1 200 OK'), llhttp parse  will return an error '6: HPE_INVALID_METHOD' when It prepare to parse the http response message 'HTTP/1.1 200 OK', I guss llhttp think that 'HTTP/1.1 200 OK' also is request message, so the '6: HPE_INVALID_METHOD' error is returned.

Is there existing any method to parsing both request and response at once?

llhttp version: v2.2.0

**Comment by pallas** [comment]
After the first request is complete, you could llhttp_reset. Alternatively, you can just use two parsers. As you observed, the implied mode is for the duration of the stream.

**Comment by wangxi19** [comment]
It works fine. Thanks advance
