### ISSUE TITLE
on_header_field_complete not called for content-length header

### ISSUE THREAD

**Issue by bryanp** [nodejs/llhttp#92]
When implementing the new `*_complete` callbacks in the [Ruby client](https://github.com/metabahn/llhttp), I noticed that the `on_header_field_complete` callback is not called for `content-length` but is called for other headers such as `content-type`. This differs from the behavior of `on_header_value_complete`, which is called for `content-length` as expected.

Is this behavior intentional?

**Comment by pallas** [comment]
No, that is not intentional. Which version of the library are you using?

**Comment by pallas** [comment]
Hmm, in my python wrapper based on v4.0.0, I do see this working as expected but I may be missing something. Can you please share request or response that isn't triggering the callback?

**Comment by pallas** [comment]
Also note #79 was a bug but it's fixed now.

**Comment by bryanp** [comment]
v3.0.1, which I just realized is _not_ the latest version. Let me update to `v4.0.0` and see if the issue persists.

**Comment by pallas** [comment]
Looks like you might be missing #81 unless I'm misunderstanding https://github.com/nodejs/llhttp/compare/v3.0.1...v4.0.0

**Comment by bryanp** [comment]
Yep, that was exactly it. Thanks for pointing me in the right direction.

**Comment by pallas** [comment]
No problem, happy to help :)
