### ISSUE TITLE
How to interrupt llhttp_execute() in events like 'on_url_complete' ?

### ISSUE THREAD

**Issue by ldcsaa** [nodejs/llhttp#98]
I try to interrupt llhttp_execute() by return -1 in events like on_url_complete, on_status_complete, on_header_field_complete, etc.
But not work. 
Would you tell me how to interrupt llhttp_execute() in such events ?

**Comment by indutny** [comment]
There is an `HPE_PAUSED` error that you can return from [some of the callbacks](https://github.com/nodejs/llhttp/blob/7e2c65de72f4034574971b15ddbe5345dbfbc50b/include/llhttp.h#L272-L301). `on_url_complete` is not one of them, but there are others that should help you. Let me know what you think!

**Comment by ldcsaa** [comment]
For example, if receive an illegal  request path like _GET /a/b/非法/路径_
I want to  interrupt parsing an return error immediately.

**Comment by indutny** [comment]
@ldcsaa perhaps you just want to build llhttp in strict mode? I believe it will do these checks for you.

**Comment by ldcsaa** [comment]
1. I had defined LLHTTP_STRICT_MODE	1, but now work.
2. Another example - A:  _on_url_complete_ receive a legeal request path, but the path does not exists, then I want to interrupt parsing an return error immediately.
3. Another example - B: _on_header_field_complete_  / _on_header_value_complete_ parses a field or value that application layer unexpected, then I want to interrupt parsing an return error immediately.

**Comment by ShogunPanda** [comment]
I'll try to implement this. Will send a PR soon.
